name: Release App

# When it will be triggered
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

# Where it will run
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Run a one-line Script
#      run: echo Hello, World!
#
#    - name: Run a multi-line script
#      run:
#          echo other action to build!
#          echo test and deploy your project.
jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.42.1/ktlint
          chmod +x ktlint
          sudo mv ktlint /usr/local/bin/

      - name: Run ktlint
        run: ktlint --reporter=plain --color always --absolute-path "**/*.kt" || exit 0

